apiVersion: v1
kind: Service
metadata:
  name: gw
  namespace: __namespace__
spec:
  type: ClusterIP
  selector:
    app: gw
    release: __release_tag__
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw
      release: __release_tag__
  template:
    metadata:
      labels:
        app: gw
        release: __release_tag__
    spec:
      containers:
        - name: gw
          image: '__docker_registry_server__/data.stack:gw.__release__'
          ports:
            - containerPort: 9080
          livenessProbe:
            httpGet:
              path: /gw/health/live
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /gw/health/ready
              port: 9080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 60
          envFrom:
          - configMapRef:
              name: config
      imagePullSecrets:
        - name: regsecret

